app:
  name: Bot
  token: your:secret_token
  tick_rate: 10
  deploy_vpn_script_url: https://raw.githubusercontent.com/spector517/veepeenet-install/v1.0.0/wireguard.py
  ssh_connection_timeout: 5_000
  ssh_exec_timeout: 20_000
  vpn_script_remote_path: /tmp/wireguard.py
  vpn_clients_remote_dir: .veepeenet/wg/clients
  remote_python_interpreter: python3


logging:
  level:
    com.github.spector517.veepeenet.bot: DEBUG

  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:veepeenet
    username: sa
    password: qwe123
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect