app:
  name: Bot
  token: your:secret_token
  tick_rate: 10
  deploy_vpn_script_url: https://raw.githubusercontent.com/spector517/veepeenet-install/main/wireguard.py
  ssh_connection_timeout: 5_000
  ssh_exec_timeout: 20_000
  vpn_script_remote_path: /tmp/wireguard.py
  vpn_clients_remote_dir: .veepeenet/wg/clients
  remote_python_interpreter: python3


logging:
  level:
    com.github.spector517.veepeenet.bot: DEBUG

  datasource:
    url: jdbc:postgresql://localhost:5432/veepeenet
    username: postgres
    password: qwe123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect