name: CI

on:
  workflow_dispatch: 

jobs:
  docker:
    runs-on: ubuntu-22.04
    steps:
    - 
      name: Checkout repo
      uses: actions/checkout@v4
    - 
      name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: ghcr.io/${{ github.actor }}/veepeenet-telegram-bot:0.1

    
